### PR TITLE
typos + Aqua CI

### PR DESCRIPTION
**Pull request by ArnoStrouwen**

### CODE REVIEW

**Comment by paulflang** [comment]
That's a shocking amount of typos detected by spell check.😅🙈

**Comment by ChrisRackauckas** [comment]
@paulflang can you look into getting tests fixed here? All I did was update the retcode check https://github.com/SciML/SBMLToolkitTestSuite.jl/pull/20 and it's failing. It would be good to keep master passing, even if it's just marking a test as broken. But here, I'm a bit confused on why anything would break: the numbers shouldn't change due to that.

**Comment by paulflang** [comment]
@ChrisRackauckas this probably has to do with an update in the dependencies. Here is a MWE that reproduces the error:
```julia
using DataFrames, ModelingToolkit, OrdinaryDiffEq

@variables t x(t)=1
D = Differential(t)
eqs = [D(x) ~ -x]
@named sys = ODESystem(eqs)
prob = ODEProblem(sys)
sol = solve(prob, Tsit5(), tspan=(0.0, 1.0))
df = DataFrame(sol)  # worked before, doesn't work now
```
```
ERROR: MethodError: no method matching SciMLBase.AbstractTimeseriesSolutionRows(::Vector{Any}, ::Vector{Type}, ::Dict{Any, Int64}, ::Vector{Float64}, ::Vector{Vector{Float64}})
```
Is this known? Do you know if/when it will be fixed?

**Comment by ChrisRackauckas** [comment]
That is not known. @AayushSabharwal did you test the dataframe generation? I can see an SII change in there. https://github.com/SciML/SciMLBase.jl/blob/master/src/tabletraits.jl#L28

**Comment by AayushSabharwal** [comment]
Table traits test passes. I'll look into the issue

**Comment by AayushSabharwal** [comment]
https://github.com/SciML/SciMLBase.jl/pull/570

**Pull request merged**
