### PR TITLE
catalyst 10

### PR DESCRIPTION
**Pull request by anandijain**

### CODE REVIEW

**Comment by anandijain** [comment]
@ChrisRackauckas is there a way to automate some part of this? only 16 days after catalyst released 10, i remembered to do this. almost like downstream testing but it automatically makes a PR with an updated compat and version

**Comment by ChrisRackauckas** [comment]
CompatHelper.jl

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SBMLToolkit.jl/pull/42

**Comment by anandijain** [comment]
oh i think at some point i just started ignoring those emails. i guess they sorted it out and it works now

**Comment by anandijain** [comment]
it seems like its not running ci on those though?

**Pull request closed without merging**
