### PR TITLE
add var_to_name

### PR DESCRIPTION
**Pull request by paulflang**
@anandijain : There is no good constructor for adding `var_to_name` in Catalyst. And the way I am using the inner constructor does not work. Could you have a look?

### CODE REVIEW

**Comment by isaacsas** [comment]
That field is not really meant to be part of the public API in ModelingToolkit systems. What are you trying to use it for?

**Comment by paulflang** [comment]
When exporting Matlab SimBiology models to SBML, variables, parameters and compartments have random strings as `id`s but meaningful `name`s. SBMLToolkit uses only `id`s, which makes it very hard to figure out what goes wrong in some SimBiology SBML exports. We thought it might be helpful to have some sort of record of the `id` to `name` mapping. But tbh, maybe this would not be all that useful.

**Comment by isaacsas** [comment]
Can you just add compartments as parameters in Catalyst, with the parameter symbol being the compartment name? Presumably they would show up in reaction rate laws anyways, so you'd need to define a corresponding parameter. You could make the convention that the Catalyst parameter's value corresponds to the size of the compartment.

We could add some basic API functions that make this easier and let you attach additional metadata to it (like the dimensionality of the compartment), and which let you query a `ReactionSystem` for the compartments.

This recent PR shows the idea of using metadata: https://github.com/SciML/ModelingToolkit.jl/pull/1560/files

**Comment by paulflang** [comment]
Using `name`s would not work, as they are not necessarily unique. I like the idea of metadata. Cause SBML compartments become Catalyst parameters. And time variable SBML parameters become Catalyst states. Metadata would help to keep track of that. In most cases just the `name` would suffice, as authors tend to give compartments, parameters and species distinctive names.

**Comment by paulflang** [comment]
Anyway, I also saw you are thinking of adding metadata for optimization experiments. Having parameter bounds, experimental conditions/disturbances, the distinction between global and condition specific experimental variables, a noise model and and observation model is an important next step to leverage SciML tools for biological problems. I think we should aim for full support of the [PEtab format](https://petab.readthedocs.io/en/latest/) for biological optimization problems. PEtab is now part of the COMBINE associated standardization efforts. It would make sense to write PEtabToolkit.jl, to import such optimization problems into SciML. Either via Catalyst or a separate package.

**Comment by ChrisRackauckas** [comment]
It would be nice to add support as a way to benchmark parameter estimation methods in more detail

**Comment by ChrisRackauckas** [comment]
> Using names would not work, as they are not necessarily unique. I like the idea of metadata. Cause SBML compartments become Catalyst parameters. And time variable SBML parameters become Catalyst states. Metadata would help to keep track of that. In most cases just the name would suffice, as authors tend to give compartments, parameters and species distinctive names.

Names have to be unique. You just use the hierarchy like is done in the component-based MTK models

**Comment by paulflang** [comment]
So I was talking about SBML. And in SBML the `name` attribute doesn't have to be unique. For instance the example on p138 of the specs, does:
```
<species id="Ca_C" name="Ca" compartment="Cytosol" initialConcentration="0.1" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false"/>
<species id="Ca_EC" name="Ca" compartment="Extracellular" initialConcentration="1000" ...
```
So when SBMLToolkit.jl imports SBML, it ignores `name`s and uses the `id` attribute. This is fine most of the time. But SimBiology exports id's like `mwdd99bb71_3cce_4706_af50_4e44b6d46a7e`. This is not very meaningful when plotting results or debugging (requires a lot of CTRL+F in the SBML atm).

Regarding benchmarking: there is a full [suite of PEtab problems to benchmark optimizers](https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab).

**Comment by paulflang** [comment]
Deprecated via #71.

**Pull request closed without merging**
