### PR TITLE
Pl/constant specs as ps

### PR DESCRIPTION
**Pull request by paulflang**
Trying Catalyst#constant-specs-as-ps.
cc @isaacsas

### CODE REVIEW

**Comment by paulflang** [comment]
@isaacsas : https://github.com/SciML/Catalyst.jl/pull/522 works for me locally. I just don't know how to best get it to work here on CI, cause when I push the Manifest I get an error that it was created with a different Julia version (using 1.7 locally) and if I don't push it I would assume that it does not find your Catalyst branch. Do I need to fix this? If so how?
Otherwise Catalyst#constant-specs-as-ps seems good to merge from my perspective.

**Comment by isaacsas** [comment]
Sounds good. I’ll try to fix up the API stuff and then make a new breaking release. Should be tomorrow evening at the latest if that works.

**Comment by paulflang** [comment]
Great, thanks!

**Comment by paulflang** [comment]
@anandijain , this PR treats constant species as parameters. It assigns them the new `isconstantspecies=true` metadata in Catalyst v12 (IIUC this allows them to participate as reactants/products and enable correct interpretation of mass action kinetics). Could you please review?

**Comment by anandijain** [comment]
lgtm

**Pull request merged**
