### PR TITLE
Only warn for events if model has events

### LINKED ISSUE #91: why are we warning about events regardless of if the model has events?
https://github.com/SciML/SBMLToolkit.jl/blob/main/src/events.jl

not a big deal though

### PR DESCRIPTION
**Pull request by xlxs4**
Closes https://github.com/SciML/SBMLToolkit.jl/issues/91

### CODE REVIEW

**Comment by paulflang** [comment]
@xlxs4 thanks! can you make a version bump to 0.1.19?

**Review by paulflang — APPROVED** [review]

**Comment by paulflang** [comment]
@xlxs4 I decided not to release a new version just for that PR and suffixed the version with `-DEV` as described [here](https://docs.sciml.ai/ColPrac/stable/#Releases). OK for you?

**Comment by anandijain** [comment]
why not just register the patch?

**Comment by paulflang** [comment]
felt a bit excessive. skimmed through the colpracs, but doesn't seem to say much about what to do in that case. so i think it is fine to trigger a new release. just did that.

**Pull request merged**
