### PR TITLE
Pl fix argument error

### LINKED ISSUE #14: tutorial does not work
I'm getting 2 errors (trying on Stanford2013 model from biomodels, with fixed relational operators in SBML):

- ODEProblem constructor is missing (import it?)
- when I import it, I get this error:
```
julia> prob = ODEProblem(odesys, [], tspan, [])
ERROR: ArgumentError: Term{Real, Nothing}[s_0265(t), s_0485(t), s_1155(t), s_0557(t), s_0128(t), s_0181(t), s_1207(t), s_1415(t), s_0657(t), s_0507(t), ....................... , s_1349(t)] are missing from the variable map.
```

Any advice?

### PR DESCRIPTION
**Pull request by paulflang**
this is to fix #14

### CODE REVIEW

**Comment by paulflang** [comment]
@ChrisRackauckas : I cannot seem to add @exaexa as a reviewer here.

**Comment by anandijain** [comment]
nobody merge this

**Comment by giordano** [comment]
> I cannot seem to add @exaexa as a reviewer here.

The dropdown menu on the right only shows members of the organisation or collaborators to the repo.

**Comment by anandijain** [comment]
dude i literally just said dont merge this

**Comment by paulflang** [comment]
oh man, i thought you meant "why does nobody merge this" rather than "don't merge this" and still wondering why you hadn't approved yet.

**Comment by anandijain** [comment]
from now on just dont merge anything yourself please

**Comment by paulflang** [comment]
well, i think i can merge myself if i have a positive review, which i thought i had. but that was a misinterpretation of your statement. so, please try to avoid phrases that could be misinterpreted by non native speakers.
anyway, what is your reason that this should not be merged?

**Pull request merged**
